### ISSUE TITLE
One of deps requires ssl in particular version?

### ISSUE THREAD

**Issue by dpc** [SAPikachu/euphonium#1]
On Fedora 23:

```
/home/dpc/lab/rust/tests/euphonium/target/debug/euctl-f93a1dbae89cb983: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
error: test failed
```

On my system I'm on `/usr/lib/libssl.so.1.0.2h`

**Comment by SAPikachu** [comment]
It is dependency of `trust-dns` and I don't see anything special in its manifest ( https://github.com/bluejekyll/trust-dns/blob/master/Cargo.toml ). Have you installed `openssl-devel` on your system (according to https://github.com/sfackler/rust-openssl )?

**Comment by dpc** [comment]
Yes.

```
Package openssl-devel-1:1.0.2h-1.fc23.x86_64 is already installed, skipping.
```

**Comment by dpc** [comment]
I reported in in the dependency itself. Closing this one. Thanks!

**Comment by SAPikachu** [comment]
OK, thanks!
